version: "3.4"

services:
  mysql-container3:
    container_name: mysql-container3
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    restart: always
    volumes:
      - mysql-container3:/var/lib/mysql:rw
    image: 'mysql:latest'
  dockerfile_spring:
    depends_on:
      - mysql-container3
    container_name: dockerfile_spring
    ports:
      - '8089:8089'
    image: aymenjbara/dockerfile_spring

  dockerfile_angular:
    depends_on:
      - dockerfile_spring
    container_name: dockerfile_angular

    ports:
      - '4200:80'
    image: aymenjbara/dockerfile_angular:2.2.2

volumes:
  mysql-container3: { }